### ISSUE TITLE
Week 13: Adding Additional User Request Support

### ISSUE THREAD

**Issue by rfitzmorris** [gw-sd-2016/Opti4Ride#2]
@cctombs @twood02 

Adding location support to both apps. Also adding view support in 4Ride Client app for all user input data needed to issue request (slider, address bar, etc). Also adding partial support for servicing user requests with an optimal tour function in the servlet. Lastly, expanded the parameters passed in a post to the server to more intelligently determine request type.

**Comment by twood02** [comment]
sounds good. keep it up!
